# Generated by Django 3.2.3 on 2021-06-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papa', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='how_many',
            field=models.CharField(db_index=True, max_length=90),
        ),
    ]
