# Generated by Django 3.2.3 on 2021-07-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papa', '0003_alter_person_how_many'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
